endpoints:
  login: 'https://uiapi.id.nowtv.it/signin/service/international'
  config: 'https://www.nowtv.it/international/static/b956eb3/config/{territory}/nowtv/nowtv/web/production/config.json'
  tokens: 'https://auth.client.ott.sky.com/auth/tokens'
  me: 'https://p.sky.com/auth/users/me'
  node: 'https://eu.api.atom.nowtv.it/adapter-calypso/v3/query/node/'
  vod: 'https://ovp.nowtv.it/video/playouts/vod'
  search: 'https://clip.search.sky.com/bff/search/v1'

client:
  config_version: '1.0.8'
  territory: 'IT'
  provider: 'NOWTV'
  proposition: 'NOWOTT'
  platform: 'ANDROIDTV'  # PC, ANDROID, ANDROIDTV
  model: 'Nvidia Shield Android TV'
  device: 'TV'  # COMPUTER, TABLET, TV,
  id: 'Z-sKxKApCe7c3dBMGAYtKU8NmWKDcWrCKobKpnVTLqc'
  drm_device_id: 'UNKNOWN'
  client_sdk: 'IE-NOWTV-ANDROID-v1' # NOWTV-WEBPLAYER-v2
  auth_scheme: 'MESSO'
  auth_issuer: 'NOWTV'

security:
  signature_hmac_key_v4: "5f8RLBppaqKGO8bwKwNifjZ6bM8zXCVwkAK7hkhq3PS4pf"
  signature_format: 'SkyOTT client="{client}",signature="{signature}",timestamp="{timestamp}",version="1.0"'
